# image will be published to ghcr.io/<user>/<name>
name: blue-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - starship
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.mozilla.firefox
        - org.videolan.VLC
      remove:
      # - org.gnome.eog

  - type: bling
    install:
      - ublue-update

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - NotoSans

  - type: systemd
    system:
      enabled:
        - ublue-update.service

  - type: yafti
    custom-flatpaks:
      - Vivaldi: com.vivaldi.Vivaldi
      - Bitwarden: com.bitwarden.desktop
      - Discord: com.discordapp.Discord
      - Steam: com.valvesoftware.Steam
      - GIMP: org.gimp.GIMP
      - Kdenlive: org.kde.kdenlive
      - Krita: org.kde.krita

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

